version: '3.8'
services:
  app:
    container_name: taiga-bridge
    build: .
    ports:
      - "8081:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ./logs:/var/log/apache2
    restart: unless-stopped
