services:
  php:
    build: .
    volumes:
      - .:/app
    expose:
      - "9000"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
